// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import BackgroundController from "./background_controller"
application.register("background", BackgroundController)

import BubblesController from "./bubbles_controller"
application.register("bubbles", BubblesController)

import FootprintsController from "./footprints_controller"
application.register("footprints", FootprintsController)

import HamburgerController from "./hamburger_controller"
application.register("hamburger", HamburgerController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import LookupController from "./lookup_controller"
application.register("lookup", LookupController)

import RedirectController from "./redirect_controller"
application.register("redirect", RedirectController)

import ShareController from "./share_controller"
application.register("share", ShareController)

import ToggleController from "./toggle_controller"
application.register("toggle", ToggleController)
